openai_manager-1.0.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
openai_manager-1.0.0.dist-info/METADATA,sha256=TYQ6HnbbLAQiFZgmqxfZg6dQN7k0VX45bNgFag2Hk2o,9354
openai_manager-1.0.0.dist-info/RECORD,,
openai_manager-1.0.0.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
openai_manager-1.0.0.dist-info/WHEEL,sha256=pkctZYzUS4AYVn6dJ-7367OJZivF2e8RA9b_ZBjif18,92
openai_manager-1.0.0.dist-info/top_level.txt,sha256=C-mf3Cq2GE2X1r0nxPNGtV7gXQ-DASSU22tpno2nYX4,28
openai_manager/__init__.py,sha256=Wsxfk8CUWIUsT5T6Q4MEphGpL-kRZnOAS11i1Tk_QvI,688
openai_manager/__pycache__/__init__.cpython-311.pyc,,
openai_manager/__pycache__/api_resources.cpython-311.pyc,,
openai_manager/__pycache__/auth_manager.cpython-311.pyc,,
openai_manager/__pycache__/exceptions.cpython-311.pyc,,
openai_manager/__pycache__/producer_consumer.cpython-311.pyc,,
openai_manager/__pycache__/serving.cpython-311.pyc,,
openai_manager/__pycache__/utils.cpython-311.pyc,,
openai_manager/api_resources.py,sha256=DVK9X7Vx6PrR-l_lfs7YhqM_WkbS8dkTPi7WyUMb5OM,1237
openai_manager/auth_manager.py,sha256=8HkiAVarVSnsof0QyuwTPEwV7ma-WKGALZW03JjfD00,10911
openai_manager/exceptions.py,sha256=iXpVcHQHhoggssxgZ8TYAb7vno1WFod_w6r4Xqft5Vo,234
openai_manager/producer_consumer.py,sha256=7DsrC-J1ZgmhRrfV0sDCvkJyvVgNeZgtJ81xTBMe5hI,8213
openai_manager/serving.py,sha256=zojSznrfPbpx_SYiIYxomVLAbykn_jj5s-fRktBJg5c,3145
openai_manager/utils.py,sha256=T-6f9UTANkAL_JRlqMW6mwX3NsZsMHPXMx1rNA0ElWc,4476
tests/__pycache__/test_serving.cpython-311.pyc,,
tests/__pycache__/test_sync_create.cpython-311.pyc,,
tests/test_serving.py,sha256=LUy77GvWWg-8yHQceMUqQ26Xa4SmT1XzVplroLyOejI,1791
tests/test_sync_create.py,sha256=16baX6rK90mSJVWJBrrkuWttUPgehZYr7pwoWEafSeo,2077
